apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: uniper-cluster-admin
rules:
- apiGroups: ["*"]
  resources: ["*"] 
  verbs: ["*"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: uniper-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: uniper-cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: s01416@uniper.energy